apiVersion: v1
kind: Service
metadata:
  name: {{ include "hackathon-todo.fullname" . }}-frontend
  labels:
    {{- include "hackathon-todo.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
  selector:
    app: frontend
