apiVersion: v1
kind: Service
metadata:
  name: {{ include "hackathon-todo.fullname" . }}-postgres
  labels:
    {{- include "hackathon-todo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
      protocol: TCP
  selector:
    app: postgres
