apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hackathon-todo.fullname" . }}-secret
  labels:
    {{- include "hackathon-todo.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.config.databaseUrl | b64enc | quote }}
  SECRET_KEY: {{ .Values.config.secretKey | b64enc | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | b64enc | quote }}
